# Builds and runs tests

FROM microsoft/dotnet:1.1.2-sdk

# NOTE 2.0.0-preview2-sdk currently causes odd build errors

WORKDIR /app

ADD ./ /app

EXPOSE 8092 9373 8080

RUN ./build.sh

ENV TARGET_HOST "localhost"

CMD dotnet run -f netcoreapp1.1 -p ./src/XProxy/XProxy.DotNetCore.csproj -- http://0.0.0.0:8092/ http://$TARGET_HOST/
